* Algunos ajustes a los scripts de generación.
* Eliminar el plugin noepgmenu porque ya no hace falta

diff --git a/unstable/make-vdr b/unstable/make-vdr
--- a/unstable/make-vdr
+++ b/unstable/make-vdr
@@ -1,6 +1,15 @@
 #!/bin/sh
 
 vdr=VDR-NG
+TC_bin=`pwd`/VDR-NG-FW/m7x0_xtc_uclibc_Linux-i686/bin
+
+if [[ ! -d "$TC_bin" ]]
+then
+    echo "ToolChain-bin dir not found: $TC_bin" 1>&2
+    exit 1
+else
+    export PATH="$TC_bin:$PATH"
+fi
 
 # Update VDR-NG from SVN
 if [[ ! -d "$vdr" ]]
@@ -12,7 +21,7 @@ fi
 # Patching VDR
 if [[ ! -f "$vdr/HISTORY-liemikuutio" ]]
 then
-	./patching ./VDR-NG ./Addons/Files/common/patches/vdr-m7x0
+	./VDR-NG-FW/patches/patch-kernel.sh ./VDR-NG ./Addons/Files/common/patches/vdr-m7x0
 fi
 
 # Compiling VDR
