+ Añadido el plugin osdajust que permite ajustar el tamaño del OSD + Actualizar el plugin EPGSearch + Algunas búsquedas de ejemplo y configuraciones para el EPGsearch + Cambiar/Añadir plugins instalados por defecto en el firmware + Por defecto no se cargarán todos los plugins y se mostrarán en un orden establecido + Desactivar webif por defecto en la versión Pro + Hacer que "make-plugins" use el mismo ToolChain que el firmware para evitar errores con versiones distintas + Otros pequeños cambios al firmware

diff --git a/unstable/make-plugins b/unstable/make-plugins
--- a/unstable/make-plugins
+++ b/unstable/make-plugins
@@ -4,6 +4,15 @@ vdr=VDR-NG
 plugins=VDR-Plugins/Source+patch
 vdr_plugins=$vdr/PLUGINS/src
 vdr_plugins_lib=$vdr/PLUGINS/lib
+TC_bin=`pwd`/VDR-NG-FW/m7x0_xtc_uclibc_Linux-i686/bin
+
+if [[ ! -d "$TC_bin" ]]
+then
+    echo "ToolChain-bin dir not found: $TC_bin" 1>&2
+    exit 1
+else
+    export PATH="$TC_bin:$PATH"
+fi
 
 # Update VDR-NG and plugins from SVN open7x0.org from SVN open7x0.org
 if [[ ! -d "$vdr" ]]
